# Basic Site Settings
title: "Muhammad Almas Khan"
name: "Muhammad Almas Khan"
description: "Doing research in IoT security and exploring Network Sciences"
locale: "en-US"
url: "https://muhammadalmaskhan.github.io"
baseurl: ""
repository: "muhammadalmaskhan/muhammadalmaskhan.github.io"
title_separator: "-"

# Author Sidebar Info
author:
  avatar: "profile.png"
  name: "Muhammad Almas Khan"
  bio: "Doing research in IoT security <br> Exploring Network Sciences"
  location: "Islamabad, Pakistan"
  employer: '<a href="http://isb.nu.edu.pk/">FAST NUCES Islamabad</a>'
  email: "muhammad.almas@nu.edu.pk"
  googlescholar: "https://scholar.google.com/citations?user=s23eUgcAAAAJ&hl=en&oi=ao"
  orcid: "https://orcid.org/0000-0002-8712-5599"
  researchgate: "https://www.researchgate.net/profile/Muhammad-Almas-Khan"
  github: "https://github.com/muhammadalmaskhan"
  linkedin: ""  # Add if you want

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Layout Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Appearance
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate

# Output
permalink: /:categories/:title/
timezone: Asia/Karachi

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
